export const PROJECTS = [
  {
    num: "01",
    title: "Ringfill",
    img: "/images/Project/RF.png",
    skills: "Next.JS, Tailwind, React Native, TypeScript, Figma",
    description: `Recharging app/website that allow the user to reachrge anywhere & anytime  using various payment methods.
    I have designed and developed the mobile app UI and made a few edits on the website `,
    github: "https://github.com/aheart500/Ringfill",
    web: "https://ringfill.com/",
    playstore:
      "https://play.google.com/store/apps/details?id=com.yusawireless.ringfill",
    figma:
      "https://www.figma.com/design/SMEFZsuyDzD7ao7rYcsoxI/Untitled?m=auto&t=cqv5s988Lkrtp8Ix-6",
  },
  {
    num: "02",
    title: "MedC",
    img: "/images/Project/medC.png",
    skills: "Next.JS, Tailwind, Shadcn/ui, TypeScript, React Native",
    description: `
Educational app for medical students features a vast collection of questions for every medical course, each accompanied by detailed answer explanations. I am responsible for developing the mobile app UI, ensuring an intuitive and user-friendly experience. Additionally, I have applied Shadcn UI to the website to enhance its visual appeal and usability.`,
    github: "https://github.com/aheart500/MedC",
  },
  {
    num: "03",
    title: "UnityCare",
    img: "/images/Project/unity.png",
    skills: "Next.JS, Tailwind, TypeScript",
    description: `This platform was developed to provide a comprehensive online solution for healthcare services. It allows patients to easily book appointments, access information about doctors and medical specialities, and stay informed with the latest medical news. The website is designed to be scalable, secure, and user-friendly. Our goal is to streamline healthcare interactions for both patients and administrators.`,
    github: "https://github.com/Karim248119/hospital",
    web: "https://unitycare.vercel.app/",
  },
  {
    num: "04",
    title: "M-market",
    img: "/images/Project/M-market.png",
    skills: "React.JS, Tailwind",
    description: `An e-market with different types of categories it has a crud operation, sign in/up functionality, payment stack & search functionality.`,
    github: "https://github.com/Karim248119/Martian-Market",
    web: "https://karim248119.github.io/Martian-Market/",
  },
  {
    num: "05",
    title: "Babel Library",
    img: "/images/Project/Library.png",
    skills: "Next.JS, Tailwind, Shadcn/ui, firebase,React Native, TypeScript",
    description: `Library app that offers a diverse collection of books, each with comprehensive information. It includes features such as a search bar, the ability to add books to your favorites, a reading progress tracker, and a dedicated screen for adding your favorite quotes. These functionalities ensure an enriched reading experience and help you keep track of your literary journey.`,
    github: "https://github.com/Karim248119/Babel-Library",
  },
  {
    num: "06",
    title: "Delivery App",
    img: "/images/Project/delivery.png",
    skills: "React Native",
    description: `A user-friendly mobile delivery app developed using React Native and Expo, focused on providing an intuitive and visually appealing experience for tracking orders and browsing delivery options. This application was designed to showcase seamless navigation and smooth user interactions, making it easy for users to explore available delivery services and monitor their orders in real time.`,
    github: "https://github.com/Karim248119/K-Dlivery",
  },
  {
    num: "07",
    title: "Heavenly Restriction",
    img: "/images/Project/HR.png",
    skills: "React Native, MongoDB, Express.JS, TypeScript, Figma",
    description: `Health care application, inspired by the Jujutsu Kaisen anime, offers a comprehensive fitness experience. It includes gym training programs, home workouts, various diet plans, and a BMI calculator. Each exercise is accompanied by an illustrative GIF demonstrating how it's done and explaining its effects on the body, making it easy for users to follow and understand their fitness routines.`,
    github: "https://github.com/Karim248119/Heavenly-Restriction",
  },
  {
    num: "08",
    title: "Lady Store",
    img: "/images/Project/lady.png",
    skills: "Next.JS, Tailwind, Shadcn/ui, firebase,React Native, Figma, Canva",
    description: ` Women's E-store application that allow you to manage and showcase women's products efficiently. The website features full CRUD functionality, enabling you to categorize products and provide comprehensive information for each item. The application ensures that all products are displayed with an attractive and intuitive user interface.`,
    github: "https://github.com/Karim248119/Lady-Store",
  },
  {
    num: "09",
    title: "COSMOS",
    img: "/images/Project/COSMOS.png",
    skills: "Next.JS, Tailwind, TypeScript, Shadcn/ui, three.js, Framer motion",
    description: `COSMOS is a visually immersive tribute to the renowned science show, exploring the universe with stunning 3D visuals and animations. Built with Next.js, Tailwind CSS, and TypeScript, it features Three.js and Framer Motion for a captivating experience. Currently optimized for desktop, this project offers a unique, interactive journey through space.`,
    github: "https://github.com/Karim248119/COSMOS",
    web: "https://cosmos-red.vercel.app/",
  },
  {
    num: "10",
    title: "Night Activities",
    img: "/images/Project/na.png",
    skills: "React Native, TypeScript, Firebase, Figma, Canva",
    description: `It's s couples app that allows you to save and share your activities effortlessly. It features a TODO screen for managing tasks, a Shared Gallery screen for storing photos, a Saved Recipes screen for your favorite dishes, and a Watch List stack that contains all IMDB movies.`,
    figma:
      "https://www.figma.com/design/evOWv5bNFT0ptlfrLXJ3kr/NA?m=auto&t=qYNbn13d2TdLqKBo-6",
  },
  {
    num: "11",
    title: "Petadopt",
    img: "/images/Project/pet.png",
    skills: "Next.JS, Tailwind",
    description: `This single-page website for pet adoption offers a clean and intuitive user interface. It includes a filtering feature to help you easily find your desired pet. Additionally, a sliding element showcases heartwarming stories from previous adopters, enhancing the overall user experience and encouraging more adoptions.`,
    github: "https://github.com/Karim248119/Petadopt",
    web: "https://k-petadopt.netlify.app/",
  },
  {
    num: "12",
    title: "K-store",
    img: "/images/Project/kstore.png",
    skills: "React.JS, Tailwind",
    description: `This e-commerce website features a wide variety of products and offers a seamless shopping experience. It includes functionalities such as saving items to a wishlist, adding products to a shopping cart, and multiple payment methods for convenient checkout.`,
    github: "https://github.com/Karim248119/K-store",
    web: "https://k-commerce.netlify.app/",
  },
  {
    num: "13",
    title: "TOP-20",
    img: "/images/Project/top.png",
    skills: "React.JS, Tailwind, Tailwind ui",
    description: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis
    magni enim cumque facere natus, voluptatibus voluptates!`,
    web: "https://top-20.netlify.app/",
  },
  {
    num: "14",
    title: "Sherlock Holmes",
    img: "/images/Project/sherlock.png",
    skills: "HTML, Tailwind, Java Script",
    description: `This portfolio landing page for the famous Sherlock Holmes boasts elegant styling and is fully responsive. It showcases Holmes' illustrious career, intriguing cases, and notable achievements in a visually appealing manner. The design ensures that the page looks great on all devices, providing an optimal viewing experience for every visitor.`,
    web: "https://karim248119.github.io/Portfolio/",
    github: "https://github.com/Karim248119/Portfolio",
  },
  {
    num: "15",
    title: "ANGORA",
    img: "/images/Project/ANGORA.png",
    skills: "HTML, Tailwind, Java Script",
    description: `Simple company landing page`,
    web: "https://karim248119.github.io/ANGORA/",
    github: "https://github.com/Karim248119/ANGORA",
  },
  {
    num: "16",
    title: "Bakery",
    img: "/images/Project/bakery.png",
    skills: "HTML, CSS, Java Script",
    description: `Simple bakery landing page`,
    web: "https://karim248119.github.io/Bakery/",
    github: "https://github.com/Karim248119/Bakery",
  },
];
